#If debug mode is active, the mod will log when items are dropped
debugMode = false
#Items to add, in the form modid:itemName:[nbtfile]:minStackSize:maxStackSize:universalChance:[monsterChance]:[bossChance]:[group1Chance]:[group2Chance]...
#Chances are %
#NBT File is a json file in the "editmobdrops" folder here in config (leave blank for none)
itemsToAdd = []
#Mob groups, in the form [EntityModid]:[EntityName]:[EntityModid]:[EntityName]...
mobGroups = []
#Mobs to clear existing drops from
mobsToClear = []
#Single mob items, in the form EntityModid:EntityName:modid:itemName:[nbtfile]:minStackSize:maxStackSize:chance
singleMobItems = [
    "corundumguardian:corundum_guardian:minecraft:gunpowder::8:15:100",
    "corundumguardian:corundum_guardian:scguns:phosphor_dust::10:20:100",
    "corundumguardian:corundum_guardian:born_in_chaos_v1:dark_metal_ingot::2:4:100",
    "corundumguardian:corundum_guardian:terramity:daemonium_chunk::2:4:100",
    "corundumguardian:corundum_guardian:scguns:sulfur_dust::10:20:100",
    "corundumguardian:corundum_guardian:jeg:gunnite_ingot::3:5:50",
    "corundumguardian:corundum_guardian:conflunce:ankh_charm::1:1:10",

    "cartoon_soul:observer:minecraft:gunpowder::8:15:100",
    "cartoon_soul:observer:scguns:phosphor_dust::10:20:100",
    "cartoon_soul:observer:scguns:niter_dust::8:15:100",
    "cartoon_soul:observer:scguns:treated_brass_blueprint::1:1:100",
    "cartoon_soul:observer:create:brass_ingot::8:15:100",
    "cartoon_soul:observer:confluence:detoxification_capsule::1:1:10",

    "cartoon_soul:dwarfgolem:create:andesite_alloy::8:15:100",
    "cartoon_soul:dwarfgolem:minecraft:gunpowder::8:15:100",
    "cartoon_soul:dwarfgolem:create:zinc_ingot::5:10:100",
    "cartoon_soul:dwarfgolem:minecraft:iron_ingot::8:15:100",
    "cartoon_soul:dwarfgolem:confluence:paladins_sheild::1:1:10",

    "cartoon_soul:hand:minecraft:gunpowder::10:20:100",
    "cartoon_soul:hand:minecraft:iron_ingot::8:15:100",
    "cartoon_soul:hand:minecraft:diamond::8:15:100",
    "cartoon_soul:hand:create:brass_ingot::5:10:100",
    "cartoon_soul:hand:confluence:hand_of_creation::1:1:10",
    "cartoon_soul:hand:terramity:angel_feather::3:6:100",
    "cartoon_soul:hand:scguns:lockewood::1:1:25",

    "cartoon_soul:furious:minecraft:gunpowder::8:15:100",
    "cartoon_soul:furious:minecraft:netherite_ingot::0:1:50",
    "cartoon_soul:furious:terramity:chthonic_crystal::3:6:100",
    "cartoon_soul:furious:terramity:raw_profanum::2:3:100",
    "cartoon_soul:furious:terramity:chthonic_crystal::3:6:100",
    "cartoon_soul:furious:terramity:daemonium_chunk::2:4:50",
    "cartoon_soul:furious:terramity:murasama::1:1:10",

    "pigzilla:pigzilla:minecraft:porkchop::10:20:100",
    "pigzilla:pigzilla:minecraft:rotten_flesh::10:15:100",
    "pigzilla:pigzilla:minecraft:gunpowder::10:15:100",
    "pigzilla:pigzilla:minecraft:diamond::7:15:100",
    "pigzilla:pigzilla:confluence:flesh_knuckles::1:1:10",

    "razor_tyrant:razor_tyrant:minecraft:iron_block::3:6:100",
    "razor_tyrant:razor_tyrant:terramity:circuit_board::1:2:100",
    "razor_tyrant:razor_tyrant:terramity:electronic_scrap::3:6:100",
    "razor_tyrant:razor_tyrant:terramity:battery::2:2:100",
    "razor_tyrant:razor_tyrant:confluence:radar::1:1:100",
    "razor_tyrant:razor_tyrant:confluence:rek_3000::1:1:10",

    "ba_bt:land_golem:minecraft:gunpowder::10:15:100",
    "ba_bt:land_golem:confluence:sun_stone::1:1:10",
    "ba_bt:land_golem:minecraft:flint::5:10:100",
    "ba_bt:land_golem:scguns:anthralite_ore::1:5:100",
    "ba_bt:land_golem:scguns:deepslate_sulfur_ore::6:10:100",
    "ba_bt:land_golem:minecraft:diamond_ore::1:5:100",
    "ba_bt:land_golem:minecraft:coal_ore::1:5:100",
    "ba_bt:land_golem:terramity:deepslate_iridium_ore::1:5:100",
    "ba_bt:land_golem:terramity:profaned_ore::1:1:50",

    "the_spino:spino:minecraft:gunpowder::2:4:100",
    "the_spino:spino:minecraft:bone::2:4:100",
    "the_spino:spino:scguns:sulfur_dust::2:4:50",

    "look:eye_of_cthulhu:minecraft:gunpowder::8:12:100",
    "look:eye_of_cthulhu:scguns:raw_phosphor::4:8:100",
    "look:eye_of_cthulhu:minecraft:diamond::3:8:100",
    "look:eye_of_cthulhu:scguns:sheol::6:8:50",
    "look:eye_of_cthulhu:scguns:raw_anthralite::8:12:100",
    "look:eye_of_cthulhu:confluence:sheild_of_cthulhu::1:1:10",

    "look:spazmatism:minecraft:gunpowder::8:12:100",
    "look:spazmatism:scguns:raw_phosphor::4:8:100",
    "look:spazmatism:scguns:sheol::7:10:50",
    "look:spazmatism:scguns:raw_anthralite::10:12:100",
    "look:retinazer:create:brass_ingot::2:4:100",
    "look:retinazer:terramity:daemonium::1:2:100",

    "look:retinazer:minecraft:gunpowder::8:12:100",
    "look:retinazer:scguns:raw_phosphor::4:8:100",
    "look:retinazer:scguns:sheol::7:10:50",
    "look:retinazer:scguns:raw_anthralite::10:12:100",
    "look:retinazer:create:brass_ingot::2:4:100",
    "look:retinazer:terramity:iridescent_shard::1:2:100",

    "mythsandlegends:black_charro:minecraft:gunpowder::10:15:100",
    "mythsandlegends:black_charro:minecraft:bone::5:15:100",
    "mythsandlegends:black_charro:terramity:lost_soul::4:8:50",
    "mythsandlegends:black_charro:terramity:empty_essence::1:1:10",
    "mythsandlegends:black_charro:scguns:treated_brass_blueprint::10:15:100",

    "hs_bosses:sand_warrior:minecraft:gunpowder::10:15:100",
    "hs_bosses:sand_warrior:minecraft:sandstone::3:5:100",
    "hs_bosses:sand_warrior:confluence:sandstorm_in_a_bottle::1:1:100",
    "hs_bosses:sand_warrior:confluence:anklet_of_the_wind::1:1:10",
    "hs_bosses:sand_warrior:scguns:sulfir_dust::10:15:100",

    "cartoon_soul:jesterknight:minecraft:gunpowder::8:12:100",
    "cartoon_soul:jesterknight:minecraft:emerald::8:12:100",
    "cartoon_soul:jesterknight:scguns:iron_blueprint::1:1:100",
    "cartoon_soul:jesterknight:scguns:sheol::6:8:100",
    "cartoon_soul:jesterknight:terramity:daemonium_chunk::8:12:100",

    "look:deerclops:minecraft:gunpowder::8:14:100",
    "look:deerclops:minecraft:copper_ingot::8:14:100",
    "look:deerclops:scguns:sulfur_chunk:::5:8:100",
    "look:deerclops:create:brass_ingot::5:8:100",
    "look:deerclops:minecraft:diamond::2:4:100",
    "look:deerclops:confluence:the_plan::1:1:10",

    "cnc:wechuge:minecraft:gunpowder::8:14:100",
    "cnc:wechuge:jeg:scrap::8:14:100",
    "cnc:wechuge:minecraft:leather::8:14:100",
    "cnc:wechuge:scguns:mas_55::1:1:50",

    "theinkarena:blot:minecraft:gunpowder::8:14:100",

    "just_in_nether:pigmar:minecraft:gunpowder::12:15:100",
    "just_in_nether:pigmar:scguns:sulfur_chunk::12:14:100",
    "just_in_nether:pigmar:minecraft:netherite_scrap::1:3:100",
    "just_in_nether:pigmar:terramity:ruby::1:5:100",

    "just_in_nether:bullkindar:minecraft:gunpowder::12:15:100",
    "just_in_nether:bullkindar:scguns:sulfur_chunk::12:15:100",
    "just_in_nether:bullkindar:minecraft:netherite_scrap::1:3:100",
    "just_in_nether:bullkindar:terramity:ruby::1:5:100",
]

